name: swimaca
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_database: ^10.4.5
  firebase_analytics: ^10.10.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/i.png
    - assets/images/i2.png
    - assets/images/i3.png
    - assets/images/i4.png
    - assets/images/i4.jpg
    - assets/images/i5r.jpg
    - assets/images/i6.jpg
    - assets/images/olimp.png