name: swimaca
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  image_picker: ^1.0.7
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  firebase_database: ^11.3.6
  firebase_analytics: ^11.4.6
  url_launcher: ^6.3.1
  file_picker: ^10.1.9
  intl: ^0.20.2
  mask_text_input_formatter: ^2.4.0
  mailer: ^6.0.1
  http: ^1.2.0
  http_parser: ^4.0.2
  html: ^0.15.4
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/i.png
    - assets/images/i2.png
    - assets/images/i3.png
    - assets/images/i4.png
    - assets/images/i4.jpg
    - assets/images/i5r.jpg
    - assets/images/i6.jpg
    - assets/images/olimp.png
    - assets/images/img.png